---

- name: create groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ user_groups }}"

- name: deploy whiteteam, blueteam, redteam users
  user:
    append: yes
    groups: "{{ (user_groups | join(',')) }}"
    name: "{{ item }}"
    password: "Braintree!"
    shell: "{{ user_shell }}"
    state: present
    update_password: on_create
  loop: "{{ authorized_users }}"

- name: install sudo package
  package:
    name: sudo
    state: present

- name: Setup sudoers.d
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    regexp: "^#includedir /etc/sudoers.d"
    validate: "visudo -cf %s"
    state: present
  when: enable_passwordless_sudo

- name: setup passwordless sudo
  template:
    src: deploy_user.j2
    dest: "/etc/sudoers.d/{{ user_name }}"
    owner: root
    group: root
    mode: 0440
    validate: "visudo -cf %s"
  when: enable_passwordless_sudo
